"""T86 — causal_root_cause: isolation experiments to build causal models.

Reads anomalies recorded in MongoDB `agent_thoughts` during a session, runs
targeted isolation probes via the forge_runner MCP tool (existing sandbox
pool), and builds a causal model: {trigger, condition, effect, confidence}.

Causal findings are stored as vulnerability metadata in MongoDB so they
surface in T27 evidence-flow view.
"""
from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from app.database.mongodb import get_agent_thoughts_collection, get_vulnerability_metadata_collection
from app.services.mcp_client import call_mcp_tool

logger = logging.getLogger(__name__)

# Keywords in agent thoughts that signal anomalies worth causal investigation
_ANOMALY_KEYWORDS = [
    "unexpected", "anomaly", "discrepancy", "inconsistent", "differs",
    "mismatch", "error rate", "timing", "race", "exception", "crash",
    "segfault", "OOM", "timeout", "retry", "flaky",
]


async def _fetch_anomalies(session_id: str, limit: int = 30) -> List[Dict[str, Any]]:
    """Pull agent_thoughts that contain anomaly signals."""
    thoughts_coll = get_agent_thoughts_collection()
    anomalies: List[Dict[str, Any]] = []
    cursor = thoughts_coll.find({"session_id": session_id}).sort("timestamp", -1).limit(200)
    async for doc in cursor:
        content = str(doc.get("content", "")).lower()
        if any(kw in content for kw in _ANOMALY_KEYWORDS):
            anomalies.append(doc)
        if len(anomalies) >= limit:
            break
    return anomalies


def _extract_trigger_hypothesis(thought_doc: Dict[str, Any]) -> Optional[Dict[str, str]]:
    """Derive a trigger/condition hypothesis from a raw thought document."""
    content = thought_doc.get("content", "")
    if not content:
        return None
    # Take the first 300 chars as the trigger description
    trigger = content[:300].strip()
    tool = thought_doc.get("tool_name", "unknown")
    return {
        "trigger": trigger,
        "tool": tool,
        "thought_id": str(thought_doc.get("_id", "")),
    }


async def _run_isolation_probe(
    session_id: str,
    trigger: str,
    tool_name: str = "forge_runner",
) -> Optional[Dict[str, Any]]:
    """Run a single isolation probe through the forge_runner MCP tool."""
    try:
        script = (
            "import sys, os\n"
            "# Isolation probe — reproduce minimal trigger\n"
            f"trigger_desc = {repr(trigger[:200])}\n"
            "print('PROBE:', trigger_desc[:80])\n"
            "# Placeholder: real probes are generated by the LLM orchestrator\n"
        )
        result = await call_mcp_tool(
            "forge_runner",
            {"session_id": session_id, "script": script, "timeout": 30},
        )
        return result
    except Exception as exc:
        logger.debug("isolation probe failed: %s", exc)
        return None


async def build_causal_model(
    session_id: str,
    vuln_id: Optional[str] = None,
    max_probes: int = 5,
) -> List[Dict[str, Any]]:
    """Build causal models from session anomalies.

    Returns a list of causal finding dicts, each stored as vulnerability
    metadata so they appear in the T27 evidence-flow UI.
    """
    anomalies = await _fetch_anomalies(session_id)
    if not anomalies:
        logger.info("causal_root_cause: no anomalies found for session=%s", session_id)
        return []

    causal_findings: List[Dict[str, Any]] = []
    probes_run = 0

    for anomaly in anomalies[:max_probes]:
        hyp = _extract_trigger_hypothesis(anomaly)
        if not hyp:
            continue

        probe_result = await _run_isolation_probe(
            session_id, hyp["trigger"], hyp["tool"]
        )
        probes_run += 1

        # Determine effect confidence from probe outcome
        effect = "undetermined"
        confidence = 0.3
        if probe_result:
            output = str(probe_result.get("output", "")).lower()
            if any(kw in output for kw in ["error", "exception", "crash", "fail"]):
                effect = "reproduced_error"
                confidence = 0.8
            elif "probe:" in output:
                effect = "probe_executed"
                confidence = 0.5

        causal_finding = {
            "causal_id": f"causal-{uuid.uuid4().hex[:8]}",
            "session_id": session_id,
            "trigger": hyp["trigger"][:300],
            "condition": f"probe via {hyp['tool']}",
            "effect": effect,
            "confidence": confidence,
            "thought_id": hyp["thought_id"],
            "created_at": datetime.now(timezone.utc),
        }
        causal_findings.append(causal_finding)

        # Store in MongoDB vulnerability_metadata for T27 evidence view
        if vuln_id:
            try:
                meta_coll = get_vulnerability_metadata_collection()
                await meta_coll.update_one(
                    {"vuln_id": vuln_id, "session_id": session_id},
                    {"$push": {"causal_findings": causal_finding}},
                    upsert=True,
                )
            except Exception as exc:
                logger.debug("causal metadata store failed: %s", exc)

    logger.info(
        "causal_root_cause: session=%s probes=%d findings=%d",
        session_id, probes_run, len(causal_findings),
    )
    return causal_findings


async def get_causal_findings(session_id: str) -> List[Dict[str, Any]]:
    """Retrieve all causal findings recorded for a session."""
    try:
        meta_coll = get_vulnerability_metadata_collection()
        results: List[Dict[str, Any]] = []
        cursor = meta_coll.find({"session_id": session_id, "causal_findings": {"$exists": True}})
        async for doc in cursor:
            for cf in doc.get("causal_findings", []):
                results.append({
                    "vuln_id": doc.get("vuln_id", ""),
                    **cf,
                })
        return results
    except Exception as exc:
        logger.warning("get_causal_findings failed: %s", exc)
        return []
